# Generated by Django 4.1.7 on 2023-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.DecimalField(decimal_places=1, max_digits=3)),
                ('recall', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
