# Generated by Django 4.1.7 on 2023-03-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
            ],
            options={"managed": True,},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("chemin", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=False)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.categorie",
                    ),
                ),
            ],
            options={"managed": True,},
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("chemin", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("accuracy", models.DecimalField(decimal_places=1, max_digits=3)),
                ("recall", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={"managed": True,},
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.BooleanField(blank=True, null=True)),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=510, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="app.image",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="app.modele",
                    ),
                ),
            ],
            options={"managed": True,},
        ),
        migrations.CreateModel(
            name="Resultat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="app.categorie",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="app.prediction",
                    ),
                ),
            ],
            options={
                "managed": True,
                "unique_together": {("categorie", "prediction")},
            },
        ),
        migrations.CreateModel(
            name="DetailsModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_modele",
                        to="app.categorie",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_modele",
                        to="app.modele",
                    ),
                ),
            ],
            options={"managed": True, "unique_together": {("modele", "categorie")},},
        ),
    ]
