# Generated by Django 4.1.7 on 2023-03-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='app.categorie')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='app.prediction')),
            ],
            options={
                'unique_together': {('categorie', 'prediction')},
            },
        ),
    ]
