# Generated by Django 4.1.7 on 2023-03-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resultat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detailsmodele',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='modele',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'managed': True},
        ),
    ]
